<?php

namespace TestBundle\Repository;

/**
 * ResponsesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsesRepository extends \Doctrine\ORM\EntityRepository
{
}
